"""Add label fields to Certification

Revision ID: aec0c924055a
Revises: 20251209_add_compliance_tasks
Create Date: 2026-01-05 09:03:17.404236+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aec0c924055a'
down_revision = '20251209_add_compliance_tasks'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Upgrade database schema to this revision.
    
    This function contains the forward migration logic.
    It is automatically generated by Alembic based on model changes.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('global_certifications', sa.Column('branding_image_url', sa.String(length=255), nullable=True, comment='URL to the official certification logo/mark'))
    # op.add_column('global_certifications', sa.Column('labeling_requirements', sa.Text(), nullable=True, comment='Specific requirements for placing the label on the product (min size, location, etc.)'))
    # op.alter_column('notification_rules', 'id',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.UUID(),
    #            existing_comment='Unique identifier for the notification rule',
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade database schema from this revision.
    
    This function contains the reverse migration logic.
    Use with caution - may result in data loss!
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification_rules', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_comment='Unique identifier for the notification rule',
               existing_nullable=False)
    op.drop_column('global_certifications', 'labeling_requirements')
    op.drop_column('global_certifications', 'branding_image_url')
    # ### end Alembic commands ###


