"""Add labeling picture fields to compliance record

Revision ID: a6e05da85878
Revises: a333a1220f19
Create Date: 2026-01-13 12:20:19.586271+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a6e05da85878'
down_revision = 'a333a1220f19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Upgrade database schema to this revision.
    
    This function contains the forward migration logic.
    It is automatically generated by Alembic based on model changes.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compliance_records', sa.Column('labeling_picture_path', sa.Text(), nullable=True, comment='MinIO object path for label picture'))
    op.add_column('compliance_records', sa.Column('labeling_picture_filename', sa.String(length=255), nullable=True, comment='Original filename of uploaded label picture'))
    op.add_column('compliance_records', sa.Column('labeling_picture_mime_type', sa.String(length=100), nullable=True, comment='MIME type of the label picture'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade database schema from this revision.
    
    This function contains the reverse migration logic.
    Use with caution - may result in data loss!
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant_devices', 'target_countries',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text('\'["ALL"]\'::json'),
               existing_nullable=True)
    op.alter_column('notification_rules', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_comment='Unique identifier for the notification rule',
               existing_nullable=False)
    op.alter_column('global_countries', 'details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Flexible country details (voltage, plugs, label requirements)',
               existing_nullable=True)
    op.alter_column('global_certifications', 'labeling_requirements',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Specific requirements for placing the label on the product (min size, location, etc.)',
               existing_nullable=True)
    op.alter_column('global_certifications', 'branding_image_url',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='URL to the official certification logo/mark',
               existing_nullable=True)
    op.drop_column('compliance_records', 'labeling_picture_mime_type')
    op.drop_column('compliance_records', 'labeling_picture_filename')
    op.drop_column('compliance_records', 'labeling_picture_path')
    # ### end Alembic commands ###


