"""add_labeling_status

Revision ID: a9dfebb3e3c0
Revises: 3c2d3600522a
Create Date: 2026-01-12 09:42:20.001819+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9dfebb3e3c0'
down_revision = '3c2d3600522a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Upgrade database schema to this revision.
    
    This function contains the forward migration logic.
    It is automatically generated by Alembic based on model changes.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compliance_records', sa.Column('labeling_status', sa.String(length=20), nullable=True, comment='Labeling status: PENDING, DONE'))
    op.alter_column('compliance_records', 'test_report_path',
               existing_type=sa.TEXT(),
               comment='MinIO object path for test report',
               existing_nullable=True)
    op.alter_column('compliance_records', 'test_report_filename',
               existing_type=sa.VARCHAR(length=255),
               comment='Original filename of uploaded test report',
               existing_nullable=True)
    op.alter_column('compliance_records', 'test_report_mime_type',
               existing_type=sa.VARCHAR(length=100),
               comment='MIME type of the test report',
               existing_nullable=True)
    op.alter_column('compliance_records', 'test_report_mime_type',
               existing_type=sa.VARCHAR(length=100),
               comment='MIME type of the test report',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade database schema from this revision.
    
    This function contains the reverse migration logic.
    Use with caution - may result in data loss!
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('compliance_records', 'test_report_mime_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='MIME type of the test report',
               existing_nullable=True)
    op.alter_column('compliance_records', 'test_report_filename',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Original filename of uploaded test report',
               existing_nullable=True)
    op.alter_column('compliance_records', 'test_report_path',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='MinIO object path for test report',
               existing_nullable=True)
    op.drop_column('compliance_records', 'labeling_status')
    # ### end Alembic commands ###


