"""Add global_glossary table

Revision ID: 3c2d3600522a
Revises: aec0c924055a
Create Date: 2026-01-07 11:05:47.508985+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c2d3600522a'
down_revision = 'aec0c924055a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Upgrade database schema to this revision.
    
    This function contains the forward migration logic.
    It is automatically generated by Alembic based on model changes.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('compliance_records', 'test_report_path', ...)
    # op.alter_column('compliance_records', 'test_report_filename', ...)
    # op.alter_column('compliance_records', 'test_report_mime_type', ...)
    # op.alter_column('global_certifications', 'branding_image_url', ...)
    # op.alter_column('global_certifications', 'labeling_requirements', ...)
    # op.alter_column('global_countries', 'details', ...)
    # op.alter_column('notification_rules', 'id', ...)
    # op.alter_column('tenant_devices', 'target_countries', ...)
    # ### end Alembic commands ###
    
    # op.create_table('global_glossary', ...)
    pass


def downgrade() -> None:
    """
    Downgrade database schema from this revision.
    
    This function contains the reverse migration logic.
    Use with caution - may result in data loss!
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant_devices', 'target_countries',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text('\'["ALL"]\'::json'),
               existing_nullable=True)
    op.alter_column('notification_rules', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_comment='Unique identifier for the notification rule',
               existing_nullable=False)
    op.alter_column('global_countries', 'details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Flexible country details (voltage, plugs, label requirements)',
               existing_nullable=True)
    op.alter_column('global_certifications', 'labeling_requirements',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Specific requirements for placing the label on the product (min size, location, etc.)',
               existing_nullable=True)
    op.alter_column('global_certifications', 'branding_image_url',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='URL to the official certification logo/mark',
               existing_nullable=True)
    op.alter_column('compliance_records', 'test_report_mime_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='MIME type of the test report',
               existing_nullable=True)
    op.alter_column('compliance_records', 'test_report_filename',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Original filename of uploaded test report',
               existing_nullable=True)
    op.alter_column('compliance_records', 'test_report_path',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='MinIO object path for test report',
               existing_nullable=True)
    # ### end Alembic commands ###


